deployment:
  replicas: 2
  image:
    owner: senthil123
    repository: pythonflaskapp
    tag: b85e8deab03cd93f906fa79a71b8cc8d73bac850
  container:
    name: python-flask-app-cont
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30112
