deployment:
  replicas: 2
  image:
    owner: memathesh
    repository: pythonflaskapp
    tag: a796ff29e06156b0afe787596f3df046556ab4cf
  container:
    name: pythonflaskapp
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30112
