deployment:
  replicas: 2
  image:
    owner: senthil123
    repository: pythonflaskapp
    tag: 70754f454a256d3bb7a73aeef07f4f96dad46f69
  container:
    name: python-flask-app-cont
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30112
